# Generated by Django 5.2.7 on 2025-11-12 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohidratos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proteina', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grasas', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_tipo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('edad', models.IntegerField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contraseña', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('genero', models.CharField(max_length=100)),
                ('condicion_medica', models.TextField(blank=True, null=True)),
                ('alergia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha', models.DateField()),
                ('peso_actual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_calorias', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_proteinas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_grasas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_carbohidratos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_consumo', to='api.alimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_consumo', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('calorias_objetivos_totales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_nutricionales', to='api.registroconsumo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_nutricionales', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calorias_diarias', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_objetivo', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_progreso', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porciones', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_alimento', to='api.alimento')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_plan', to='api.plannutricional')),
            ],
            options={
                'unique_together': {('plan', 'alimento')},
            },
        ),
    ]
